### ISSUE TITLE
0BDFDB.plugin.js & 0PluginLibrary.plugin.js

### ISSUE THREAD

**Issue by zeronobody0** [Lightcord/filehashes#9]
I am writing on behalf of the people who wrote 0BDFDB.plugin.js and 0PluginLibrary.plugin.js, because I use those libraries. Here is the source code for [0BDFDB.plugin.js](https://raw.githubusercontent.com/mwittrien/BetterDiscordAddons/master/Library/0BDFDB.plugin.js), and here is the source for [0PluginLibrary.plugin.js](https://raw.githubusercontent.com/rauenzi/BDPluginLibrary/master/release/0PluginLibrary.plugin.js).

**Comment by JeanOUINA** [comment]
should be good.
